# Generated by Django 2.0.4 on 2018-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collezione',
            name='id',
        ),
        migrations.AddField(
            model_name='bottle',
            name='id_bottle',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collezione',
            name='id_coll',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
