# Generated by Django 2.0.4 on 2018-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0002_auto_20180430_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='id_bottle',
        ),
        migrations.RemoveField(
            model_name='collezione',
            name='id_coll',
        ),
        migrations.AddField(
            model_name='bottle',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collezione',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bottle',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='collezione',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
