# Generated by Django 2.0.4 on 2018-04-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0003_auto_20180430_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
