# Generated by Django 2.0.4 on 2018-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0004_auto_20180430_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='bottle_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bottle',
            name='year_bottled',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='distillery',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
