# Generated by Django 2.0.4 on 2018-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0005_auto_20180430_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='purchased',
            new_name='purchased_date',
        ),
        migrations.AddField(
            model_name='bottle',
            name='purchased_place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
