# Generated by Django 2.0.4 on 2018-04-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0006_auto_20180430_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='purchased_place',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
