# Generated by Django 2.0.4 on 2018-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0007_auto_20180430_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='category',
            field=models.CharField(choices=[('SC', 'Scotch'), ('IR', 'Irish'), ('BO', 'Bourbon'), ('CA', 'Canadian'), ('RY', 'Rye'), ('JA', 'Japan'), ('OT', 'Other countries'), ('--', 'Unknown')], default='--', max_length=2),
        ),
    ]
