# Generated by Django 2.0.4 on 2018-05-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0009_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
