# Generated by Django 2.0.4 on 2018-05-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0010_auto_20180521_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='whisky_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collezioni.Category'),
            preserve_default=False,
        ),
    ]
