# Generated by Django 2.0.4 on 2018-05-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collezioni', '0011_bottle_whisky_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='category',
        ),
    ]
